SELECT name, age+102 as Current_age , survived FROM `train` WHERE survived = "1";
SELECT name, 10000 as Compession , survived FROM `train`;
SELECT DISTINCT sex survived FROM `train`;
SELECT DISTINCT pclass , sex FROM `train`;
SELECT DISTINCT name , pclass , survived FROM `train` WHERE survived = 1 AND pclass = 3;
SELECT DISTINCT name , age , survived FROM `train` WHERE survived = 1 AND age>30;
SELECT DISTINCT name , age , survived FROM `train` WHERE survived = 1 AND age BETWEEN 12 AND 18;
SELECT name , sex FROM train WHERE sex like "male";
SELECT name , sex FROM train WHERE sex IN ("male" , "female");
SELECT name , sex FROM train WHERE sex NOT IN ("male" , "female");
SELECT name , sex FROM train WHERE name like "a%"OR name like "A%";
SELECT name , sex FROM train WHERE name like "%tom%";
SELECT name , sex FROM train WHERE name like "%tom%";
SELECT name , sex FROM train WHERE name like "a_____";
UPDATE users SET name = "Shantnu";
UPDATE passenger SET age = 23 WHERE country like "India";
UPDATE passenger SET country = "INDIA" and destination = "CP" WHERE country like "ind";
UPDATE passenger SET country = "INDIA" where country LIKE "in%";
DELETE FROM passenger WHERE pass_id = 6;
DELETE FROM passenger WHERE destination LIKE "gu%";